# proxypool remote server url. Blank for http://127.0.0.1:8080
server_url: https://free.zdl.im/clash/proxies?type=trojan,vmess,ssr
# server_url: https://example.proxypoolserver.com/clash/proxies?type=vmess


# For your local server
request: http   # http / https
domain: wf168.netlify.app        # default: 127.0.0.1
port:           # default: 80

cron_interval: 60       # default: 15  minutes
show_remote_speed: true # default false

healthcheck_timeout:    # default 5
healthcheck_connection: 300 # default 100

speedtest: true             # default false
speed_connection: 10      # default 5
speed_timeout: 3         # default 10
